[project]
site_name = "Jershlabs Tutorials"
repo_url = "https://github.com/jershbytes/tutorials"
repo_name = "jershbytes/tutorials"


nav = [
    {"Home" = "index.md"},
    {"Guides" = [
        {"Linux" = [
            {"Mounting Droves" = "linux/mounting-drives.md"},
            {"Setting up WSL" = "linux/setting-up-wsl.md"},
    ]},
        {"Git" = [
            {"Git Gud" = "git/setting-up-git.md"},
    ]},
        {"Ansible" = [
            {"Setting up Semaphore" = "ansible/setting-up-semaphore.md"}
    ]},
        {"Terraform" = [
            {"Setting up Terraform" = "terraform/setting-up-terraform.md"}
    ]},
    ]},
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
logo = "lucide/square-library"
repo = "fontawesome/brands/git-alt"

[project.theme]
favicon = "images/homelab.png"
